Fix missing dependency on obj/base/rust_logger_cxx_generated/rust_logger.rs.o
In file included from gen/base/logging/rust_logger.rs.cc:1:
In file included from ../../base/logging/rust_log_integration.h:12:
In file included from ../../base/logging.h:19:
In file included from ../../base/files/file_path.h:113:
../../base/trace_event/base_tracing_forward.h:11:10: fatal error: 'base/tracing_buildflags.h' file not found
   11 | #include "base/tracing_buildflags.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

and

In file included from gen/base/logging/rust_logger.rs.cc:1:
In file included from ../../base/logging/rust_log_integration.h:12:
../../base/logging.h:26:10: fatal error: 'build/chromeos_buildflags.h' file not found
   26 | #include "build/chromeos_buildflags.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Bug: 405811719
Change-Id: If8a43c571ebf449e42310fe05f0d5152e9f684d2
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6382054
Commit-Queue: Fumitoshi Ukai <ukai@google.com>
Auto-Submit: Fumitoshi Ukai <ukai@google.com>
Reviewed-by: Takuto Ikuta <tikuta@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1436662}
NOKEYCHECK=True
GitOrigin-RevId: 1fad8dd1da37cff5d638ec1ed076406cdff33d1b