base: Make internal namespace in `BASE_FEATURE` unique per feature
The `BASE_FEATURE_INTERNAL_2_ARGS` macro now uses a unique namespace `base_feature_internal_##feature` to prevent ambiguous namespace error:
```
error: reference to 'base_feature_internal' is ambiguous
...
candidate found by name lookup is 'content::base_feature_internal'
...
candidate found by name lookup is 'content::(anonymous namespace)::base_feature_internal'
```

A new test is added to cover this case.

Enabled-by-default-reason: refactoring

Bug: 436274260
Change-Id: I87b4a602687a9062278a6c86d7aba64855e0c4be
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6917813
Commit-Queue: Xiaohan Wang <xhwang@chromium.org>
Reviewed-by: Daniel Cheng <dcheng@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1512806}
NOKEYCHECK=True
GitOrigin-RevId: 0de577551bb391f7cc17171ceb942ef304ff7be7